baseURL = "https://tronghieu1201.github.io/aws-fcj-learning-journey/"
defaultContentLanguage = "en"
relativeURLs = false
canonifyURLs = false

# Theme
theme = "hugo-theme-learn"

# For search functionality
[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "workshop"
  # Git hub repo link
  editURL = ""
  description = ""
  author = "Giáp Trọng Hiếu"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# ==========================================
# Languages
# ==========================================
[Languages]
  [Languages.en]
    title = "Internship Report"
    weight = 1
    label = "English"

  [[Languages.en.menu.shortcuts]]
    name = "<i class='fab fa-aws'></i> AWS Study Group - Blog"
    identifier = "AWS Study Group"
    url = "https://awsstudygroup.com"
    weight = 20

  [Languages.vi]
    title = "Báo cáo thực tập"
    weight = 2
    label = "Tiếng Việt"

  [[Languages.vi.menu.shortcuts]]
    name = "<i class='fab fa-aws'></i> AWS Study Group - Blog"
    identifier = "AWS Study Group"
    url = "https://awsstudygroup.com"
    weight = 20

  [[Languages.vi.menu.shortcuts]]
   name = "<i class='fab fa-facebook'></i> AWS Study Group - Nhóm FB"
    identifier = "AWS Study Group VN"
    url = "https://www.facebook.com/groups/awsstudygroupfcj"
    weight = 20


